### ISSUE TITLE
获取分布式机器id好像有一个问题

### ISSUE THREAD

**Issue by childewuque** [TaXueWWL/snowalker-shardingjdbc-demo#1]
如果 机器名（snowalker） 是 abc或bca或cba，sum值是一样的

//========code===========
String snowalker = "abc";
int [] snowalkerCodePoints = StringUtils.toCodePoints(snowalker);
long sum = 0;
for (int i = 0; i < snowalkerCodePoints.length; i++) {
    sum += snowalkerCodePoints[i];
    System.out.println("i=" + i + "--snowalkerCodePoints[" + i + "]=" + snowalkerCodePoints[i]);
}
System.out.println("sum=" + sum);

**Comment by tao4git** [comment]
执行获取库索引的方法，会存在库索引超出的情况。
public static long getDbIndexByMod(Object obj,int dbCount,int tbCount) {
        long tbRange = getModValue(obj, tbCount);
        BigDecimal bc = new BigDecimal(tbRange);
        BigDecimal[] results = bc.divideAndRemainder(new BigDecimal(dbCount));
        return (long)results[0].intValue();
    }
当分成2个库，每个库4张表的时候，表的数量是8，这个时候对表数量取余很可能取到5到7的数字，再来取商的时候就会出现2和3，但是库索引只有0和1.

**Comment by TaXueWWL** [comment]
关于 childewuque  的问题，这里就需要业务自己控制机器名的生成。关于 tao4git 提到的已修复
